apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo-deployment
  namespace: default
spec:
  replicas: 3
  strategy:
    rollingUpdate:  ##由于replicas为3,则整个升级,pod个数在2-4个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      nodeSelector:
        project: ops
      containers:
      - image: registry-vpc.cn-beijing.aliyuncs.com/sy-ops/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: Always
        name: jenkins-demo
        ports:
          - containerPort: 9090
        env:
        - name: branch
          value: <BRANCH_NAME>

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-ingress
  namespace: default
spec:
  type: NodePort
  selector:
    app: jenkins-demo   
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 30210

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-demo-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: demo.sy.soyoung.com
      http:
        paths:
          - path: /
            backend:
              serviceName: jenkins-demo-service
              servicePort: 9090