apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: registry-vpc.cn-beijing.aliyuncs.com/sy-ops/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: Always
        name: jenkins-demo
        ports:
          - containerPort: 9090
        env:
        - name: branch
          value: <BRANCH_NAME>

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-service
spec:
  selector:
    app: jenkins-demo   
  ports:
    - name: web
      port: 9090
      targetPort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-demo-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: demo.sy.soyoung.com
      http:
        paths:
          - path: /  
            backend:
              serviceName: jenkins-demo-service
              servicePort: 9090
