apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: default
spec:
  replicas: 1
  nodeSelector:
    project: ops
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: registry-vpc.cn-beijing.aliyuncs.com/sy-ops/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: Always
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
        ports:
          - containerPort: 9090
            name: web
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
  namespace: default
  labels:
    app: jenkins-demo
spec:
  ports:
    - name: web
      port: 9090
      targetPort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-demo-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: demo.sy.soyoung.com
      http:
        paths:
          - backend:
              serviceName: jenkins-demo
              servicePort: 9090